// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnjuagqC3nJtnJVxlLRonc0OwtBFaKAgM',
    appId: '1:902663136576:web:ae996d25e84e8e18e8c6a5',
    messagingSenderId: '902663136576',
    projectId: 'akaadapp',
    authDomain: 'akaadapp.firebaseapp.com',
    storageBucket: 'akaadapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9FBZwSIo4Ju46UJqrGUnxxbg9dWYuORs',
    appId: '1:902663136576:android:1995a7cffb846498e8c6a5',
    messagingSenderId: '902663136576',
    projectId: 'akaadapp',
    storageBucket: 'akaadapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCObTTRqAN79nWkHUbdLt3Ij7ktLgrefRE',
    appId: '1:902663136576:ios:bc187a140a1c86d3e8c6a5',
    messagingSenderId: '902663136576',
    projectId: 'akaadapp',
    storageBucket: 'akaadapp.appspot.com',
    iosBundleId: 'com.example.akaad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCObTTRqAN79nWkHUbdLt3Ij7ktLgrefRE',
    appId: '1:902663136576:ios:bc187a140a1c86d3e8c6a5',
    messagingSenderId: '902663136576',
    projectId: 'akaadapp',
    storageBucket: 'akaadapp.appspot.com',
    iosBundleId: 'com.example.akaad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnjuagqC3nJtnJVxlLRonc0OwtBFaKAgM',
    appId: '1:902663136576:web:f04061e35a768ea4e8c6a5',
    messagingSenderId: '902663136576',
    projectId: 'akaadapp',
    authDomain: 'akaadapp.firebaseapp.com',
    storageBucket: 'akaadapp.appspot.com',
  );
}
